obj-m := helloworld.o
helloworld-objs := hello_world.rust.o

CARGO ?= cargo

export c_flags

# $(src)/target/x86_64-linux-kernel-module/$(BUILD)/libhello_world.a: cargo_will_determine_dependencies
# 	cd $(src); RUST_TARGET_PATH=$(src)/.. $(CARGO) +nightly xbuild --target=x86_64-linux-kernel-module

.PHONY: cargo_will_determine_dependencies

%.rust.o: target/x86_64-linux-kernel-module/$(BUILD)/lib%.a
	$(LD) -r -o $@ --whole-archive $<
